#! /bin/sh 
set -eux

COSMO_LIBDIR="./libcosmo"

if [ ! -f $COSMO_LIBDIR/cosmopolitan.h ]; then
    echo "<<<SUPERCONFIGURE>>> cosmopolitan.h does not exist in $COSMO_LIBDIR!!!!"
    exit 1
fi

echo "<<<SUPERCONFIGURE>>> cosmopolitan.h exists in $COSMO_LIBDIR, assuming other files exist as well"

echo "<<<SUPERCONFIGURE>>> Running configure"
LD_LIBRARY_PATH="" ./configure \
    --prefix="" \
    --enable-shared=no --enable-static=yes \
    --disable-readline --disable-fast-install \
    --disable-threadsafe \
    --disable-debug --disable-tcl \
    --disable-load-extension \
    --enable-all --with-pic \
    OPT="" \
    CCSHARED="" \
    LINKFORSHARED="" \
    PKG_CONFIG="" \
    CC="gcc" \
    CFLAGS="-Wall -Wno-strict-prototypes -Wno-unused-value \
      -std=c99 -static \
      -fno-pie -no-pie -fno-omit-frame-pointer \
      -mno-red-zone -pg -mnop-mcount \
      -nostdinc -nostdlib \
      -I./header_stubs \
      -include $COSMO_LIBDIR/cosmopolitan.h" \
    LDFLAGS="-static -nostdlib -nostdinc -fno-pie \
      -no-pie -mno-red-zone \
      -include $COSMO_LIBDIR/cosmopolitan.h" \
    LIBS="\
      -Wl,--gc-sections -fuse-ld=bfd \
      -Wl,-T,$COSMO_LIBDIR/ape.lds \
      -include $COSMO_LIBDIR/cosmopolitan.h \
      $COSMO_LIBDIR/crt.o \
      $COSMO_LIBDIR/ape.o \
      $COSMO_LIBDIR/cosmopolitan.a"

echo "<<<SUPERCONFIGURE>>> Running make"
make -j4

echo "<<<SUPERCONFIGURE>>> removing cosmopolitan.a from libsqlite3.a"
ar d ./.libs/libsqlite3.a cosmopolitan.a
